# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20171220_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '部门表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息表'},
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='depart',
            new_name='department',
        ),
    ]
