# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='a@abc.com', max_length=20, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='x', max_length=16, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
