# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='tutor',
            new_name='headmaster',
        ),
        migrations.RenameField(
            model_name='classlist',
            old_name='memo',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='courserecord',
            old_name='course_memo',
            new_name='course_instruction',
        ),
        migrations.RenameField(
            model_name='courserecord',
            old_name='homework_memo',
            new_name='homework_instruction',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='memo',
            new_name='instruction',
        ),
        migrations.RenameField(
            model_name='studyrecord',
            old_name='stu_memo',
            new_name='stu_instruction',
        ),
    ]
