# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_auto_20171224_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='headmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage_classes', to='app03.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.UserInfo', verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此客户是转介绍自内部学员,请在此处选择内部学员姓名', null=True, on_delete=django.db.models.deletion.CASCADE, to='app03.Customer', verbose_name='转介绍自学员'),
        ),
    ]
