# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_auto_20171224_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='qq',
            new_name='QQ',
        ),
    ]
