# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0006_auto_20171227_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, '正在跟进'), (2, '已成单'), (3, '15天未成单'), (4, '3天未跟进')], default=1, verbose_name='状态')),
                ('memo', models.CharField(max_length=100, verbose_name='更多信息')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.UserInfo', verbose_name='顾问')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=16, verbose_name='客户姓名'),
        ),
        migrations.AddField(
            model_name='customerdistribution',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.Customer', verbose_name='客户'),
        ),
    ]
