# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0008_auto_20171227_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_limit', models.IntegerField(verbose_name='最大分配客户数量')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.UserInfo', verbose_name='课程顾问')),
            ],
        ),
        migrations.AlterModelOptions(
            name='customerdistribution',
            options={'verbose_name_plural': '客户分配表'},
        ),
    ]
