# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0010_auto_20171227_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app03.UserInfo', verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_consult_date',
            field=models.DateField(verbose_name='最后跟进日期'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recv_date',
            field=models.DateField(verbose_name='顾问接单日期'),
        ),
        migrations.AlterField(
            model_name='customerdistribution',
            name='dist_date',
            field=models.DateField(auto_now_add=True, verbose_name='分配日期'),
        ),
    ]
