# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0011_auto_20171228_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(verbose_name='咨询日期'),
        ),
    ]
