# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0014_auto_20171228_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信ID'),
        ),
    ]
