# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0018_auto_20180102_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbac.User', verbose_name='关联账户'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
